# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0774beab3dc5d1c7b5a22f4bedcc89f67a1576b58e7436458fd0cd7c788eb62e50bebd75d3c8403b5cc50a2bd02772edac6efd3f6ff20686c386a0a1c0b4bfcb

test:
  secret_key_base: f74711f5699ddea6ac530a3f0d64eb57ea9c7d0bd3f849b6c4cb9270acf8fa1bf5bd585a10910641e126c1500f72da722063ace86f755e08d376aa759764e00a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
